### ISSUE TITLE
Compatibility with Bootstrap 5

### ISSUE THREAD

**Issue by johaven** [PerfectMemory/ngx-contextmenu#1]
Is there a plan to make the project compatible with bootstrap 5?

Currently there is not much missing for it to work, the menu is activated well but the dimensions are not good.

**Comment by sroucheray** [comment]
Hi @johaven and thanks for asking and for being the first to submit an issue !

Bootstrap is an hidden peer dependency of the original project and remain it in this fork in version 6 and 7. Hidden because it uses the HTML structure of Bootstrap's dropdown and is well styled when you import Bootstrap's styles. Peer because it is not required to have it, you can simply style the context menu by yourself.

This said, my plan is to remove the Bootsrap dependency all together and provide theming capability in the next major release 8.x. 
It will be a CSS file to import providing a good default styling. This file will come with a bunch of CSS variables that you'll be able to change to apply your own variations.
I will also provide different variations of theming CSS files based on those variables, coming in their own CSS files (dark theme and so on). You will be able to use directly if you will.
Finally you will still be able to develop your own theme without importing the default one, either by copying it or from scratch.

**Comment by johaven** [comment]
With Angular 12 top and left was correctly calculated and now with Angular 13 position: "static" is set.

**Angular 12**
<img width="1363" alt="Capture d’écran 2022-02-17 à 18 59 26" src="https://user-images.githubusercontent.com/5459596/154542736-a6fc27f7-30cc-44f1-9238-dcda1bb6b2c4.png">

**Angular 13**
<img width="1299" alt="Capture d’écran 2022-02-17 à 18 59 18" src="https://user-images.githubusercontent.com/5459596/154542885-f2e3607c-bf41-4912-bb75-b2b420e9abfe.png">

**Comment by johaven** [comment]
Solved by importing: '~@angular/cdk/overlay-prebuilt.css'
