### ISSUE TITLE
PerfectMemory/ngx-contextmenu 7.0.0 not working in ipad

### ISSUE THREAD

**Issue by priyankasingh444** [PerfectMemory/ngx-contextmenu#24]
Describe the bug
"@perfectmemory/ngx-contextmenu": "^7.0.0", with Angular 13 working in web and andriod but in ipad it is not working.

To Reproduce
https://perfectmemory.github.io/ngx-contextmenu/?path=/story/context-menu-demo--demo

long press in text , context menu is not showing

Expected behavior
Context menu should work in ipad (ios devices) same as it is working in web and android.

**Comment by sroucheray** [comment]
There is a bug on iOS. It does not support `contextmenu` event on long press https://bugs.webkit.org/show_bug.cgi?id=213953

**Comment by priyankasingh444** [comment]
@sroucheray @abrisse @jperville @vtabary 
In Angular 12 i m using "ngx-contextmenu": "^5.1.1" it is working fine in iOS, but After migrated to angular 13 ngx-contextmenu does not support with angular 13 . so i have tried to use this PerfectMemory/ngx-contextmenu 7.0.0 but it does not support in ipad(iOS devices) . PrimeNG  context menu is also working with iOS

**Comment by sroucheray** [comment]
@priyankasingh444 could you provide a minimal setup on https://stackblitz.com/ of "ngx-contextmenu" 5.1.1 working with iOS. Because since my fork I have not changed the way we handle context menu event. This is done through the standard "contextmenu" event here in original repo https://github.com/isaacplmann/ngx-contextmenu/blob/master/projects/ngx-contextmenu/src/lib/contextMenu.attach.directive.ts#L14 and here in this repo https://github.com/PerfectMemory/ngx-contextmenu/blob/master/projects/ngx-contextmenu/src/lib/directives/context-menu/context-menu.directive.ts#L85

BTW please be kind not to spam @abrisse @jperville and @vtabary by pinging them as they do not maintain this repo.

**Comment by sroucheray** [comment]
Since I have no answer, I close this issue. Please comment if you have updates.
